# Generated by Django 5.1 on 2024-08-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Article's title")),
                ('description', models.CharField(max_length=300, verbose_name='Short description of the Article (for SEO)')),
                ('body', models.TextField(verbose_name="Article's body")),
                ('image', models.ImageField(upload_to='Articles images')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Job title')),
                ('description', models.TextField(verbose_name='Job description')),
            ],
        ),
    ]
