# Generated by Django 5.1 on 2024-09-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your name')),
                ('phone', models.CharField(max_length=100, verbose_name='Your phone')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Your company')),
                ('order_from', models.CharField(max_length=200, verbose_name='The Order will be shipped from')),
                ('order_to', models.CharField(max_length=200, verbose_name='The Order will be shipped to')),
            ],
            options={
                'verbose_name': "Customer's Order",
                'verbose_name_plural': "Customer's Orders",
            },
        ),
    ]
